_core:
  default_config_hash: LgxHz6qCb0m-eh51Kxc-UcBUzyQt4AtMTIqN7FS80o8
exclude:
  node: {  }
  paragraph: {  }
text_to_prepend_to_title: 'Clone of'
clone_status: false
create_group_relationships: true
