name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - docker
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export Image for ${{ matrix.arch }}
        run: |
          docker buildx build \
            --platform linux/${{ matrix.arch }} \
            -f docker/Dockerfile \
            -t config-tool:${{ matrix.arch }} \
            --load .

      - name: Save Docker image to tar file
        run: |
          docker save config-tool:${{ matrix.arch }} -o config-tool-${{ matrix.arch }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-tool-image-${{ matrix.arch }}
          path: config-tool-${{ matrix.arch }}.tar

  publish-multiarch:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image to GHCR
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f docker/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/config-tool:${VERSION} \
            -t ghcr.io/${{ github.repository_owner }}/config-tool:latest \
            --push .
