name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - docker
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t config-tool:latest .

      - name: Save Docker image to tar file
        run: |
          docker save config-tool:latest -o config-tool.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-tool-image
          path: config-tool.tar

      - name: Log in to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker tag config-tool:latest ghcr.io/${{ github.repository_owner }}/config-tool:${VERSION}
          docker tag config-tool:latest ghcr.io/${{ github.repository_owner }}/config-tool:latest
          docker push ghcr.io/${{ github.repository_owner }}/config-tool:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/config-tool:latest
