name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docker-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ppuc-config-tool:latest .

      - name: Save Docker image to tar file
        run: |
          docker save ppuc-config-tool:latest -o ppuc-config-tool.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ppuc-config-tool-image
          path: ppuc-config-tool.tar
